apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: pvc1
  containers:
    - name: container2
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: storage

