kind: PersistentVolume
apiVersion: v1
metadata: 
  name: pv1
  labels:
   app: pv
spec:
  storageClassName: vim
  capacity:
    storage: 1Gi
  accessModes:
   - ReadWriteMany
  hostPath:
     path: /vim/volume
  persistentVolumeReclaimPolicy: Delete

