kind: Pod
apiVersion: v1
metadata: 
  name: pod1
spec:
  nodeSelector:
    label: node2
  containers:
   - name: container1
     image: nginx
  tolerations:
    - key: color
      value: red
      effect: NoSchedule
